<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Wendy" ignored="1" name="test1" tests="2" failures="1" timestamp="12 abr 2018 06:12:51 GMT" time="0.045" errors="0">
  <testcase name="first" time="0.011" classname="samples.SampleTest"/>
  <testcase name="second" time="0.003" classname="samples.SampleTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at samples.SampleTest.second(SampleTest.java:18)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- second -->
  <testcase name="third" time="0.0" classname="samples.SampleTest">
    <ignored/>
  </testcase> <!-- third -->
</testsuite> <!-- test1 -->
